apiVersion: 1

datasources:
  - name: MongoDB
    type: mongodb-grafana-datasource
    access: proxy
    url: mongodb://mongodb:27017
    jsonData:
      database: api_logs
    version: 1
    editable: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
